У меня получылся но не все))
AbdurahimNasirov/VUE.todolist pull request #1
Opened 2022-02-05 13:38 UTC by AbdurahimNasirov

2022-02-05 13:46 UTC, twixy123 commented on src/App.vue
>  <style lang="scss">
scoped, работай только со scoped

2022-02-05 13:52 UTC, twixy123 commented on src/components/searchAuth/SearchAuth.vue
> +<script>
всегда всем компонентам давай имя
name: 'SeatchAuth'

2022-02-05 13:56 UTC, twixy123 commented on src/components/searchAuth/SearchAuth.vue
> +<template>
Если создаешь папку с названием searchAuth, не нужно потом внутри создавать файл SearchAuth.vue
Либо создай просто файл SearchAuth.vue
Либо создай папку SearchAuth и внутри создай файл index.vue
Если этот компонент еще где то используется но ты не делаешь его глобальным - то создавай этот компонент в /components/app/SearchAuth.vue
Если этот компонент будет глобальным то создавай через папку /components/SearchAuth/index.vue

2022-02-05 13:57 UTC, twixy123 commented on src/components/titleBlock/Title.vue
> +<template>
почему ты назвал его title?
Лучше назвать logo

2022-02-05 13:57 UTC, AbdurahimNasirov commented on src/components/searchAuth/SearchAuth.vue
> +<script>
а ок

2022-02-05 13:58 UTC, twixy123 commented on src/components/todoForm/TodoForm.vue
> +      <button type="submit" class="">
если не используешь class, то тогда удали этот атрибут

2022-02-05 13:59 UTC, twixy123 commented on src/components/todoForm/TodoForm.vue
> +    <h1 class="form__title">~ Today I need to ~</h1>
у тебя на одной странице два раза используется h1, это не правильно.
На странице может быть только один раз <h1></h1>
Лучше поставь h2

2022-02-05 14:01 UTC, twixy123 commented on src/components/todoForm/TodoForm.vue
> +    <form @submit.prevent="addNewTodo()">
не нужно вызывать метод
@submit.prevent="addNewTodo()" -> @submit.prevent="addNewTodo"

2022-02-05 14:07 UTC, twixy123 commented on src/components/todoList/TodoItem.vue
> +    ...mapGetters(["setTodos"]),
getter не может быть с названием set. 
Либо просто todos либо getTodos

2022-02-05 14:10 UTC, twixy123 commented on src/components/todoList/TodoList.vue
> +  async mounted() {
почему снова mounted навернху?
подключай eslint, он будет подсвечить как нужно правильно. Посмотри мой eslint.rc в моем проекте

должно быть
props
data
computed
created
mounted
methods

2022-02-05 14:12 UTC, twixy123 commented on src/components/todoList/TodoList.vue
> +    await this.getTodoBasicFunc();
что за название метода getTodoBasicFunc?
getTodos просто
Если будет одинаковое название из store и внутри компоенента, в сторе используй [пространство имен](https://vuex.vuejs.org/ru/guide/modules.html#%D0%BF%D1%80%D0%BE%D1%81%D1%82%D1%80%D0%B0%D0%BD%D1%81%D1%82%D0%B2%D0%B0-%D0%B8%D0%BC%D0%B5%D0%BD)

2022-02-05 14:14 UTC, AbdurahimNasirov commented on src/components/todoList/TodoList.vue
> +  async mounted() {
🤦‍♂️

2022-02-05 14:17 UTC, twixy123 commented on src/components/todoList/TodoList.vue
> +    ...mapActions(["getTodos"]),
например здесь лучше будет сделать так
... mapActions({
      dispatchGetTodos: 'getTodos',
    }),

2022-02-05 14:28 UTC, twixy123 commented on src/components/searchAuth/SearchAuth.vue
> +      });
Не создавай в компоненте body для реквеста.
Лучше в самом сторе создавать этот объект
Создаешь метод getTodos и в нем пишешь и methods и url. 
Не нужно в компоненте писать какой метод и какой url

2022-02-05 14:44 UTC, twixy123 commented on src/components/titleBlock/Title.vue
> +export default {};
всегда добавляй name

2022-02-05 14:45 UTC, twixy123 commented on src/components/todoForm/TodoForm.vue
> +            title: todoTitle,
не создавай отдельную переменную
title: todoTitle => title: this.todoName

2022-02-05 14:47 UTC, twixy123 commented on src/components/todoList/TodoList.vue
> +        selected: false,
all по умолчанию должен быть selected: true

2022-02-05 14:58 UTC, twixy123 commented on src/components/todoList/TodoList.vue
> +  },
сделай это через computed
data () {
  return {
    filterType: null (когда all) / true (когда Completed) / false ( когда Active )
    ....
  }
}
computed: {
  filteredTodos: {
    let todos = this.gettersGetTodos
    if (this.filterType === null) return todos
    return this.gettersGetTodos.filter(todo => todo.completed === this.filterType)
  }
}
methods: {
  filterTodosWithTypes(type){
    switch (type):{
      case 'Completed':
      this.filterType = true
      break;
      case 'Active':
      this.filterType = false
      break;
      case 'All':
      this.filterType = null
      break;
    }
  }
}

2022-02-05 15:02 UTC, twixy123 commented on src/store/index.js
> +            s.todos.find(todo => todo.id === data.id ? todo = data : console.log('e polucilos update') )
что ты тут вообще написал? Не правильно вообще!
const findedTodos = s.todos.find(todo => todo.id === data.id)
for (const key in data) {
        if (Object.hasOwnProperty.call(data, key)) {
          const element = data[key];
          this._vm.$set(findedTodos, key, element)
        }
      }

2022-02-05 15:04 UTC, twixy123 commented on src/store/index.js
> +        setTodos: s => s.todos
не правильно setTodos в getters писать
setTodos -> getTodos

2022-02-05 15:05 UTC, twixy123 commented on src/store/index.js
> +        async deleteTodos({dispatch, commit}, reqBody) {
Ты же только 1 todo удаляешь, зачем писать deleteTodos?
deleteTodos -> deleteTodo

2022-02-05 15:06 UTC, twixy123 commented on src/store/index.js
> +        async patchTodos({dispatch, commit}, reqBody) {
Ты же только 1 todo изменяешь, зачем писать patchTodos?
patchTodos -> patchTodo

2022-02-05 15:06 UTC, twixy123 commented on src/store/index.js
> +        async addTodos({dispatch, commit}, reqBody) {
Ты же только 1 todo добавляешь, зачем писать addTodos?
addTodos -> addTodo

2022-02-05 15:08 UTC, twixy123 requested changes
на переделку
————
store/index.js
——
state: todos
——
actions: getTodos {
  получает данные из localStorage
  mutation[setTodos]
}
addNewTodo {
  добавляет новый todo в localStorage
 mutation[setTodo]
}
removeTodo {
  удаляет todo из localStorage
 mutation[removeTodo]
}
——
 mutation: setTodos {
  устанавливает todos в state[todos]
}
setTodo {
  устанавливает новый todo в state[todos]
}
removeTodo {
  удаляет todo из state[todos]
}
——
getter: getTodos ( будет следить за изменениями в state[todos] )

————

App.vue
——
created: actions[getTodos]

————
TodoList.vue
——
v-for="todo in "getter[getTodos]"

————
TodoItem.vue
——
methods:
addTodo: action[addNewTodo]
removeTodo: actions[removeTodo]

2022-02-06 19:20 UTC, twixy123 commented on src/App.vue
> +    }
можно написать проще
 if (!localStorage.getItem("Todos")) localStorage.setItem("Todos", JSON.stringify([]));
 this.getTodos();

2022-02-06 19:28 UTC, twixy123 commented on src/components/todos/TodoItem.vue
>    <li class="todo" :class="todo.completed ? 'completed' : ''">
:class="todo.completed ? 'completed' : ''" => :class="{completed: todo.completed}"

2022-02-06 19:29 UTC, twixy123 commented on src/components/todos/TodoItem.vue
>      (this.todoTitle = this.todo.title), (this.completed = this.todo.completed);
почему этот код в скобках и в одну строку?

2022-02-06 19:33 UTC, twixy123 commented on src/store/index.js
> +            if (res.length != 0) {
старайся использовать === вместо == и !== вместо !=

2022-02-07 14:39 UTC, merged